### ISSUE TITLE
Displaying coordinates on axes

### ISSUE THREAD

**Issue by PMassicotte** [MikkoVihtakari/PlotSvalbard#2]
Hi @MikkoVihtakari, thank you for the package. I am producing this map, but I would like to display actual geographical coordinates (degdecimal) instead of the km. Is it possible?

``` r
 
 library(PlotSvalbard)
#> Loading required package: ggplot2
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'PlotSvalbard'
#> The following object is masked from 'package:dplyr':
#> 
#>     select
 
 rm(list = ls())
 
 coords <- sf::st_as_sf(tibble(lon = c(-50, -35), lat = c(50, 90)), coords = c("lon", "lat"), crs = 4326) %>%
   sf::st_transform(crs = "+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")
 
 station_coords <- sf::st_as_sf(tibble(lon = c(-63.78953333), lat = c(67.47973333)), coords = c("lon", "lat"), crs = 4326) %>%
   sf::st_transform(crs = "+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")
 
basemap("panarctic", limits = sf::st_bbox(coords)[c(1, 3, 2, 4)], bathymetry = TRUE, bathy.detailed = TRUE, land.size = 0.01, base_size = 10) +
   geom_point(aes(x = -2222852, y = -1094283), color = "red", size = 0.25) +
   theme(legend.text = element_text(size = 6)) +
   theme(legend.title = element_text(size = 8)) +
   theme(legend.key.size = unit(0.25, "cm"))
```

![](https://i.imgur.com/mCJPLf9.png)

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MikkoVihtakari** [comment]
Thanks for the reproducible example :) Printing the labels as decimal degrees is not currently possible for the "panarctic" map. Presenting latitudes on y-axis in polar stereographic projections is problematic. As you see the 60 degree line almost reaches the bounding box, but not quite. The latitude breaks on the y-axis would not be very informative as the lines curve so much, but in theory, implementing this feature should be possible and useful for smaller maps. The feature has been implemented in the `deg_grid` function using some basic geometry and making a similar feature to the `deg_grid_polar` function would require some adjustment of the code. 

I have not needed this feature, but can mark it as a feature request. If you have time, you may try to adapt the code and suggest how to write the `deg_grid_polar` function. If not, I suggest that you adjust the latitude and longitude lines using the lon/lat.interval arguments to fit your map and manually add the decimal degree labels using a vector graphic editor.

**Comment by MikkoVihtakari** [comment]
Thanks for the reproducible example :) Printing the labels as decimal degrees is not currently possible for the "panarctic" map. Presenting latitudes on y-axis in polar stereographic projections is problematic. As you see the 60 degree line almost reaches the bounding box, but not quite. The line curves across the entire map. The latitude breaks on the y-axis would not be very informative as the lines curve so much, but in theory, implementing this feature should be possible and useful for smaller maps. The feature has been implemented in the `deg_grid` function using some basic geometry and making a similar feature to the `deg_grid_polar` function would require some adjustment of the code.

I have not needed this feature, but can mark it as a feature request. If you have time, you may try to adapt the code and suggest how to write the deg_grid_polar function. If not, I suggest that you adjust the latitude and longitude lines using the lon/lat.interval arguments to fit your map and manually add the decimal degree labels using a vector graphic editor.

Btw, PlotSvalbard contains the `transform_coord` function to transform the coordinates for your data.frame.

**Comment by PMassicotte** [comment]
Thank you for your answer! I will look at your suggestion and see what I can do. Thanks for the great package.

**Comment by MikkoVihtakari** [comment]
This issue has been addressed in the upgraded version of PlotSvalbard, which is not called ggOceanMaps: https://mikkovihtakari.github.io/ggOceanMaps/index.html
