### ISSUE TITLE
Caspian Sea appears same colour as land

### ISSUE THREAD

**Issue by marianagarciacriado** [MikkoVihtakari/PlotSvalbard#4]
Hi Mikko, thanks a lot for the great package! 
I have been using the pan-arctic map to display a few points in a polar projection, and just noticed that the Caspian Sea appears to be coloured the same as the chosen colour for the land instead of white - you can see in the image attached. Is there anything I can do to colour the Caspian Sea in white too? Thanks in advance!

![polar_traits_map_new](https://user-images.githubusercontent.com/32198706/81073859-24d55280-8ee0-11ea-9538-a23d33c834e5.png)

Here is my code in case that helps:
```
plant.coords <- transform_coord(x = coord.data, lon = "Lon", lat = "Lat",
                                new.names = c("lon.utm", "lat.utm"),
                                map.type = 'panarctic', verbose = FALSE, bind = TRUE)

(tundra.map <- basemap("panarctic", limits = 30, land.col = "#c9c7c1") + 
    geom_point(data = plant.coords, aes(x = lon.utm, y = lat.utm, colour = TraitShort), 
               alpha = 0.4, size = 10) + 
    scale_colour_manual(values = c("purple", "orange","darkgreen"), 
                        guide = guide_legend(title = "Plant Traits", override.aes = list(alpha = 1)), 
                        labels = c("Height", "Seed Mass", "SLA")))
```

**Comment by MikkoVihtakari** [comment]
Yup. That is a mystic issue I still don't understand. It has been solved (by sheer luck) in the new package that is to replace PlotSvalbard: https://mikkovihtakari.github.io/ggOceanMaps/index.html

If you'll find a solution, please let me know. If not, please use the new package which is an improved version of PlotSvalbard.

**Comment by marianagarciacriado** [comment]
Great, thanks for the quick response Mikko. I have tried with ggOceanMaps and indeed the Caspian Sea appears coloured in white, but I've found one issue setting the map limits. 

If I set my projection limit to 30 degrees latitude, the land seems to be cut closer to the limit - see example below. I have tried with different integers and the issue occurs with values between 30 and 39, and then it works fine at 40 degrees. From what I see in the documentation, the values can be any "single integer between 30 and 88". Am I doing anything wrong here? Thanks again!
![Screenshot 2020-05-05 at 15 16 23](https://user-images.githubusercontent.com/32198706/81076640-cc07b900-8ee3-11ea-9101-1a2d951617b4.png)

**Comment by MikkoVihtakari** [comment]
Thanks for pointing this out. This is a bug that has to be fixed eventually when I find the time. For now, you may recreate the Arctic shapefiles using 20 lat cut point instead of 30. See here: https://mikkovihtakari.github.io/ggOceanMaps/articles/premade-shapefiles.html

Just have the landshapes on workspace using the same object name (arctic_land) and it hopefully over-rides the one in the package. 

I.e. 

```
NEDPath <- "<path to your Natural Earth Data shapefiles>"
world <- rgdal::readOGR(paste(NEDPath, "ne_10m_land/ne_10m_land.shp", sep = "/"))
islands <- rgdal::readOGR(paste(NEDPath, "ne_10m_minor_islands/ne_10m_minor_islands.shp", sep = "/"))
world <- rbind(world, islands)

arctic_land <- clip_shapefile(world, c(-180, 180, 20, 90))
arctic_land <- sp::spTransform(arctic_land, sp::CRS(sp::proj4string(arctic_bathy)))
arctic_land <- rgeos::gBuffer(arctic_land, byid = TRUE, width = 0)

```

**Comment by MikkoVihtakari** [comment]
This bug has been fixed in ggOceanMaps: https://github.com/MikkoVihtakari/ggOceanMaps

Please use that package instead of PlotSvalbard.
