### ISSUE TITLE
Move ts_plot() to ggOceanMaps

### ISSUE THREAD

**Issue by janstrauss1** [MikkoVihtakari/PlotSvalbard#5]
Hi @MikkoVihtakari,

Would it be possible to move the `ts_plot()` function to `ggOceanMaps`?

Many thanks,
Jan

**Comment by MikkoVihtakari** [comment]
Thanks for the suggestion Jan. The functions have been moved to a separate package, called [ggOceanPlots](https://github.com/MikkoVihtakari/ggOceanPlots), which I plan to submit to CRAN when I'll find the time. As I mentioned in the [oce thread](https://github.com/dankelley/oce/issues/1812#issuecomment-828589416), I am not against if these functions are moved to oce or "ggoce" instead.
